-- LuaMapScriptExample: a minimal Perlin-noise island generator.
--
-- A Lua map script must define TWO functions:
--   GetMapScriptInfo() -> { name = ..., description = ... }   (metadata for the new-game screen)
--   GenerateMap(ctx)   -> boolean                              (the generator itself)
--
-- The ctx table provides:
--   ctx.params  - read-only MapParameters (size, shape, wrap, advanced settings...)
--   ctx.seed    - the map seed
--   ctx.perlin(x, y, seed, {scale=..., nOctaves=..., persistence=..., lacunarity=...})
--   ctx.random() / ctx.randomInt(min, max)
--   ctx.map     - the TileMap being generated (see below)
--   ctx.log(msg)
--
-- ctx.map helpers: getTile(x,y) / getAllTiles() / getWidth/getHeight/getRadius/getShape/isWrapped,
--   assignContinents(), addStartingLocation(x, y, nationName), getStartingLocations(),
--   clearStartingLocations(), setTransients(), normalizeTiles(), floodFill(x, y, terrain?),
--   generateClimate(), spreadCoasts(maxExtension?), generateMountains(elevationExponent?),
--   generateRivers(), generateIce(), convertTerrains(),
--   normalizeStartPlot(x, y, opts?), distributeLuxuries(opts?), distributeStrategics(opts?),
--   strategicBalanceStarts(opts?)
--
-- Tile helpers (from map.getTile / getAllTiles / floodFill):
--   position{x,y}, getX/getY, baseTerrain, isLand/isWater/isCoast, isHill(), isMountain(),
--   isImpassable(), hasTerrainFeature(name), getTerrainFeatures(), temperature/getTemperature/setTemperature,
--   humidity/getHumidity/setHumidity, getLatitude/getLongitude, getContinent(),
--   hasResource, resourceName, resourceAmount, hasImprovement, improvementName, isRiver(),
--   isNaturalWonder(), isAdjacentToFreshWater(), getBaseYield(stat), getNeighbors(), getTilesInDistance(r),
--   setTerrain(name), addTerrainFeature(name), removeTerrainFeature(name), removeAllTerrainFeatures(),
--   setResource(name, amount), removeResource(), setImprovement(name), removeImprovement(),
--   setRoad(), setRailroad(), removeRoad(), setNaturalWonder(name)

function GetMapScriptInfo()
    return {
        name = "Lua Example: Perlin Islands",
        description = "A simple island map generated by a Lua script: raises land with Perlin " ..
            "noise, adds mountains, rivers, resources and a starting location."
    }
end

function GenerateMap(ctx)
    local params = ctx.params
    local map = ctx.map
    local log = ctx.log

    log("Starting Lua map generation, seed=" .. tostring(ctx.seed))

    -- 1. Raise land with Perlin noise. The map starts out as ocean.
    --    Iterate with getAllTiles() - rectangular map coordinates are centered on
    --    (0,0) and can be negative (see ctx.params.bounds).
    local landThreshold = 0.05
    local tiles = map.getAllTiles()
    for _, tile in ipairs(tiles) do
        local n = ctx.perlin(tile.getX(), tile.getY(), 42.0, { scale = 25.0, nOctaves = 4 })
        if n > landThreshold then
            tile.setTerrain("Grassland")
        end
    end

    -- 2. Continent assignment (needed before climate generation)
    map.assignContinents()

    -- 3. Climate, mountains, coasts, rivers
    map.generateClimate()
    map.generateMountains(params.elevationExponent)
    map.spreadCoasts()
    map.generateRivers()

    -- 4. Put a starting location at the center (or nearest land) and balance it
    local bounds = params.bounds
    local cx = math.floor((bounds.minX + bounds.maxX) / 2)
    local cy = math.floor((bounds.minY + bounds.maxY) / 2)
    local startTile = map.getTile(cx, cy)
    if not startTile.isLand then
        -- find the nearest land tile via flood fill neighbours
        local found = false
        for r = 1, math.max(bounds.maxX - bounds.minX, bounds.maxY - bounds.minY) do
            local ring = startTile.getTilesInDistance(r)
            for _, t in ipairs(ring) do
                if t.isLand then
                    cx, cy = t.getX(), t.getY()
                    found = true
                    break
                end
            end
            if found then break end
        end
    end
    map.addStartingLocation(cx, cy, "")
    map.normalizeStartPlot(cx, cy, { minFood = 4, minProd = 3, minLuxuries = 2 })
    map.distributeLuxuries({ perPlayer = 2, minDistance = 4 })
    map.distributeStrategics({ perPlayer = 1 })

    log("Lua map script finished, start at (" .. cx .. ", " .. cy .. ")")
    return true
end
