# android
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false

# gradle
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx16384m -XX:MaxMetaspaceSize=2048m -XX:+HeapDumpOnOutOfMemoryError

#alternate band-aid for the `jvm target compatibility should be set to the same Java version` problem:
#kotlin.jvm.target.validation.mode = IGNORE
