package com.unciv.logic.scripting

import java.io.File

/**
 * Generates an EmmyLua-compatible type definition file for the mod Lua API, consumed by
 * the LuaLS language server (VSCode extension "Lua" by sumneko) so mod authors get
 * autocompletion, hover docs and immediate method-name checking while writing scripts.
 *
 * The file is generated from [LuaAPI.apiCatalog]; every API name in the catalog appears in
 * the output (verified by tests), so the definitions can never drift from the implementation.
 * Parameter/return signatures are a curated best-effort: precise for the common patterns,
 * `fun(...)` for the rest. Run via `./gradlew desktop:generateDocs` - never edit the
 * generated file by hand.
 */
class LuaApiDefinitionWriter {

    companion object {
        /** Output path relative to the assets dir (the generateDocs task's working dir). */
        private const val outputFileName = "../../docs/Modders/lua-api.lua"

        /** Context table -> generated class name. */
        private val classNameByOwner = mapOf(
            "ctx" to "UncivCtx",
            "civ" to "UncivCiv",
            "city" to "UncivCity",
            "unit" to "UncivUnit",
            "tile" to "UncivTile",
            "game" to "UncivGame",
            "store" to "UncivStore"
        )

        private val ownerOrder = listOf("civ", "city", "unit", "tile", "game", "store", "ctx")

        private fun signatureFor(owner: String, method: String): String {
            LuaApiDocs.entriesByName[owner]?.get(method)?.let { return it.signature }
            // Fallback: APIs missing from LuaApiDocs (should not happen, tests enforce coverage)
            // accept anything; plain fields are unknown-typed
            return if (looksLikeMethod(method)) "fun(...)" else "any"
        }

        private fun looksLikeMethod(method: String): Boolean =
            method.startsWith("get") || method.startsWith("is") || method.startsWith("has") ||
                method.startsWith("can") || method.startsWith("add") || method.startsWith("set") ||
                method.startsWith("remove") || method.startsWith("clear") || method.startsWith("trigger") ||
                method.startsWith("declare") || method.startsWith("grant") || method.startsWith("consume") ||
                method.startsWith("use") || method.startsWith("heal") || method.startsWith("take") ||
                method.startsWith("teleport") || method.startsWith("attack") || method.startsWith("find") ||
                method.startsWith("upgrade") || method.startsWith("destroy") || method.startsWith("reveal") ||
                method.startsWith("does") || method.startsWith("evaluate") || method.startsWith("count") ||
                method.startsWith("log")
    }

    /** Pure generation - the tests call this; the docs task writes the result to disk. */
    fun generate(): String {
        val out = StringBuilder()
        out.appendLine("---@meta")
        out.appendLine()
        out.appendLine("-- Unciv Lua 模组 API 类型定义（自动生成，请勿手工编辑）")
        out.appendLine("-- Generated by LuaApiDefinitionWriter - never edit by hand.")
        out.appendLine("-- Regenerate with: ./gradlew desktop:generateDocs")
        out.appendLine("--")
        out.appendLine("-- 用法 / Usage: install the LuaLS language server (VSCode extension \"Lua\" by sumneko),")
        out.appendLine("-- then point workspace.library at this file in .luarc.json - you get autocompletion,")
        out.appendLine("-- hover docs and immediate checking of ctx.civ.addGoldd(...)-style typos.")
        out.appendLine("-- Note: signatures are best-effort; the runtime game (mod checker / mod-ci) is authoritative.")
        out.appendLine()

        for (owner in ownerOrder) {
            val names = LuaAPI.apiCatalog[owner] ?: continue
            out.appendLine("---@class ${classNameByOwner[owner]}")
            for (name in names) {
                out.appendLine("---@field $name ${signatureFor(owner, name)}")
            }
            out.appendLine()
        }
        return out.toString().trimEnd() + "\n"
    }

    /** Writes the generated definitions into the docs folder (generateDocs task, working dir = assets). */
    fun write() {
        File(outputFileName).writeText(generate())
    }
}
