package com.unciv.logic.scripting

/**
 * 生成面向模组作者的 Lua API 参考文档（`docs/Modders/Lua-API-Reference.md` 与
 * `docs/zh/Modders/Lua-API-Reference.md`），内容全部来自 [LuaApiDocs]，
 * 与 [LuaAPI.apiCatalog] 保持一致（由 LuaApiDocsTests 校验），文档永不与实现漂移。
 *
 * 教程部分（`Lua-Modding.md`）由人工维护并链接到本文件；新增/修改 API 时只需
 * 同步 [LuaApiDocs] 与 [LuaAPI.apiCatalog]，再运行 `./gradlew desktop:generateDocs`。
 * **严禁人工编辑本生成产物。**
 */
object LuaApiReferenceWriter {

    /** 文档展示顺序（与 lua-api.lua 的类型定义顺序一致） */
    private val ownerOrder = listOf("civ", "city", "unit", "tile", "game", "ctx", "store")

    private fun ownerTitle(owner: String, language: String?): String = when (owner) {
        "civ" -> if (language == null) "civ — Civilization" else "civ — 文明"
        "city" -> if (language == null) "city — City" else "city — 城市"
        "unit" -> if (language == null) "unit — Unit" else "unit — 单位"
        "tile" -> if (language == null) "tile — Tile" else "tile — 地块"
        "game" -> if (language == null) "game — Global" else "game — 全局"
        "ctx" -> if (language == null) "ctx — Context" else "ctx — 上下文"
        "store" -> if (language == null) "ctx.store — Persistent Storage" else "ctx.store — 持久化存储"
        else -> owner
    }

    private fun categoryTitle(category: LuaApiDocs.Category, language: String?): String = when (category) {
        LuaApiDocs.Category.Property -> if (language == null) "Properties" else "属性"
        LuaApiDocs.Category.Query -> if (language == null) "Query methods" else "查询方法"
        LuaApiDocs.Category.Write -> if (language == null) "Write methods" else "写入方法"
    }

    /** 从 EmmyLua 签名提取调用形式：fun(a: T, b: U) -> "a, b"；fun() -> "" */
    private fun callArguments(signature: String): String {
        if (!signature.startsWith("fun(")) return ""
        val params = signature.removePrefix("fun(").substringBefore(")").trim()
        if (params.isEmpty()) return ""
        return params.split(", ").joinToString(", ") { it.substringBefore(":") }
    }

    /** 生成全文；language 为 "Simplified_Chinese" 时输出中文版 */
    fun generate(language: String?): String {
        val out = StringBuilder()
        out.appendLine("<!-- 本文件由 LuaApiReferenceWriter 自动生成，请勿手动编辑。 -->")
        out.appendLine("<!-- Generated by LuaApiReferenceWriter - never edit by hand. -->")
        out.appendLine("<!-- 重新生成 / Regenerate with: ./gradlew desktop:generateDocs -->")
        out.appendLine()
        if (language == null) {
            out.appendLine("# Lua API Reference")
            out.appendLine()
            out.appendLine("This page is generated from the game code and lists every function and property of the")
            out.appendLine("Lua context tables (`ctx`). It can never drift from the implementation - when a new API is")
            out.appendLine("added, this page is regenerated together with the type definitions (`lua-api.lua`).")
            out.appendLine()
            out.appendLine("For tutorials, triggers and editor setup see [Lua Mod Scripts](Lua-Modding.md).")
            out.appendLine()
            out.appendLine("> **Note on signatures**: types follow the EmmyLua style used by the LuaLS language server")
            out.appendLine("> (`lua-api.lua`); `|nil` means the value may be absent, `string[]` a list of strings.")
        } else {
            out.appendLine("# Lua API 参考")
            out.appendLine()
            out.appendLine("本页面由游戏代码自动生成，列出 Lua 上下文表（`ctx`）的全部函数与属性。它永远不会与实现")
            out.appendLine("脱节——新增 API 时，本页面与类型定义（`lua-api.lua`）会一起重新生成。")
            out.appendLine()
            out.appendLine("教程、触发方式与编辑器设置见 [Lua 脚本](Lua-Modding.md)。")
            out.appendLine()
            out.appendLine("> **关于签名**：类型采用 LuaLS 语言服务器（`lua-api.lua`）使用的 EmmyLua 风格；")
            out.appendLine("> `|nil` 表示该值可能为空，`string[]` 表示字符串列表。")
        }
        out.appendLine()

        for (owner in ownerOrder) {
            val entries = LuaApiDocs.entries[owner] ?: continue
            out.appendLine("## ${ownerTitle(owner, language)}")
            out.appendLine()
            for (category in LuaApiDocs.Category.entries) {
                val members = entries.filter { it.category == category }
                if (members.isEmpty()) continue
                out.appendLine("**${categoryTitle(category, language)}**:")
                out.appendLine()
                if (category == LuaApiDocs.Category.Property) {
                    out.appendLine("`" + members.joinToString("`, `") { it.name } + "`")
                    out.appendLine()
                    continue
                }
                out.appendLine("```lua")
                val width = members.maxOf { it.name.length + callArguments(it.signature).length } + 4
                for (entry in members) {
                    val call = "${owner}.${entry.name}(${callArguments(entry.signature)})"
                    val desc = if (language == null) entry.desc else entry.descZh
                    out.appendLine(call.padEnd(width) + "-- " + desc)
                }
                out.appendLine("```")
                out.appendLine()
            }
        }
        return out.toString().trimEnd() + "\n"
    }
}
