package com.unciv.logic.scripting

import com.unciv.UncivGame
import java.io.File

/**
 * Generates an EmmyLua-compatible type definition file for the mod Lua API, consumed by
 * the LuaLS language server (VSCode extension "Lua" by sumneko) so mod authors get
 * autocompletion, hover docs and immediate method-name checking while writing scripts.
 *
 * The file is generated from [LuaAPI.apiCatalog]; every API name in the catalog appears in
 * the output (verified by tests), so the definitions can never drift from the implementation.
 * Parameter/return signatures are a curated best-effort: precise for the common patterns,
 * `fun(...)` for the rest. Run via `./gradlew desktop:generateDocs` - never edit the
 * generated file by hand.
 */
class LuaApiDefinitionWriter {

    companion object {
        /** Output path relative to the assets dir (the generateDocs task's working dir). */
        private const val outputFileName = "../../docs/Modders/lua-api.lua"

        /** Context table -> generated class name. */
        private val classNameByOwner = mapOf(
            "ctx" to "UncivCtx",
            "civ" to "UncivCiv",
            "city" to "UncivCity",
            "unit" to "UncivUnit",
            "tile" to "UncivTile",
            "game" to "UncivGame",
            "store" to "UncivStore"
        )

        private val ownerOrder = listOf("civ", "city", "unit", "tile", "game", "store", "ctx")

        private val headerLines: List<String> get() = listOf(
            "-- Unciv Lua 模组 API 类型定义（自动生成，请勿手工编辑）",
            "-- Generated by LuaApiDefinitionWriter - never edit by hand.",
            "-- Regenerate with: ./gradlew desktop:generateDocs",
            "-- Unciv version: ${UncivGame.VERSION.text} (build ${UncivGame.VERSION.number})",
            "--",
            "-- 用法 / Usage: install the LuaLS language server (VSCode extension \"Lua\" by sumneko),",
            "-- then point workspace.library at this file in .luarc.json - you get autocompletion,",
            "-- hover docs and immediate checking of ctx.civ.addGoldd(...)-style typos.",
            "-- Note: signatures are best-effort; the runtime game (mod checker / mod-ci) is authoritative.",
        )
    }

    /** Pure generation - the tests call this; the docs task writes the result to disk. */
    fun generate(): String = generateLuaTypeDefinitions(headerLines, ownerOrder, classNameByOwner, LuaApiDocs.entriesByName)

    /** Writes the generated definitions into the docs folder (generateDocs task, working dir = assets). */
    fun write() {
        File(outputFileName).writeText(generate())
    }
}

/**
 * EmmyLua 类型定义生成核心：遍历 owner 输出 `---@class` + `---@field`。
 * 游戏内 API（[LuaApiDefinitionWriter]）与地图脚本 API（[LuaMapApiDefinitionWriter]）共用；
 * 签名来自对应的文档数据表，fallback `fun(...)`/`any` 仅为防御（测试强制全覆盖）。
 */
internal fun generateLuaTypeDefinitions(
    headerLines: List<String>,
    ownerOrder: List<String>,
    classNameByOwner: Map<String, String>,
    entriesByName: Map<String, Map<String, LuaApiDocEntry>>,
    /** 每条 @field 末尾追加的说明注释（如中文说明），null 则不追加 */
    fieldComment: ((LuaApiDocEntry) -> String?)? = null,
    /** 附加的辅助类定义块（options 表等不在 catalog 中的形状），追加在末尾 */
    extraSections: String? = null
): String {
    val out = StringBuilder()
    out.appendLine("---@meta")
    out.appendLine()
    for (line in headerLines) out.appendLine(line)
    out.appendLine()

    for (owner in ownerOrder) {
        val entries = entriesByName[owner] ?: continue
        out.appendLine("---@class ${classNameByOwner[owner]}")
        for (entry in entries.values) {
            val line = "---@field ${entry.name} ${entry.signature}"
            val comment = fieldComment?.invoke(entry)
            out.appendLine(if (comment.isNullOrEmpty()) line else "$line $comment")
        }
        out.appendLine()
    }
    if (extraSections != null) {
        out.appendLine(extraSections.trimIndent())
        out.appendLine()
    }
    return out.toString().trimEnd() + "\n"
}
