package com.unciv.logic.scripting

import com.unciv.UncivGame
import java.io.File

/**
 * Generates an EmmyLua-compatible type definition file for the Lua **map-script** API
 * (`docs/Modders/lua-map-api.lua`), consumed by the LuaLS language server so mod authors
 * get autocompletion while writing `GenerateMap(ctx)` scripts.
 *
 * The file is generated from [LuaMapGenApiDocs]; every API in the catalog appears in the
 * output (verified by tests), so the definitions can never drift from the implementation.
 * Helper shapes that are not part of the catalog (Perlin/start-plot option tables,
 * starting-location and script-info result shapes) are appended as [extraSections].
 * Run via `./gradlew desktop:generateDocs` - never edit the generated file by hand.
 */
class LuaMapApiDefinitionWriter {

    companion object {
        /** Output path relative to the assets dir (the generateDocs task's working dir). */
        private const val outputFileName = "../../docs/Modders/lua-map-api.lua"

        /** Context table -> generated class name. */
        private val classNameByOwner = mapOf(
            "ctx" to "UncivMapCtx",
            "params" to "UncivMapParams",
            "size" to "UncivMapSize",
            "bounds" to "UncivMapBounds",
            "map" to "UncivMapGenMap",
            "tile" to "UncivMapGenTile"
        )

        private val ownerOrder = listOf("ctx", "params", "size", "bounds", "map", "tile")

        private val headerLines: List<String> get() = listOf(
            "-- Unciv Lua 地图脚本 API 类型定义（自动生成，请勿手工编辑）",
            "-- Generated by LuaMapApiDefinitionWriter - never edit by hand.",
            "-- Regenerate with: ./gradlew desktop:generateDocs",
            "-- Unciv version: ${UncivGame.VERSION.text} (build ${UncivGame.VERSION.number})",
            "--",
            "-- 用法 / Usage: point workspace.library at this file in .luarc.json (together with",
            "-- unciv-api.lua) - you get autocompletion and hover docs for GenerateMap(ctx) scripts.",
            "-- Note: the runtime game (mod checker / mod-ci) remains authoritative for signatures.",
        )

        /**
         * 辅助类定义（options 表与返回值形状，不在 apiCatalog 中，跟随生成器源码维护）。
         * 说明文案与 LuaMapGenApiDocs 的 descZh 一致。
         */
        private val extraSections = """
            ---@class UncivPerlinOpts
            ---@field scale? number 噪声观测距离（默认 30.0）
            ---@field nOctaves? number 八度数（默认 6）
            ---@field persistence? number 振幅缩放（默认 0.5）
            ---@field lacunarity? number 频率缩放（默认 2.0）

            ---@class UncivStartPlotOpts
            ---@field freshwater? boolean 确保邻接淡水（默认 true）
            ---@field minFood? number 内环最小食物（默认 4）
            ---@field minProd? number 内环最小产能（默认 3）
            ---@field minLuxuries? number 3 格内最少奢侈种类（默认 2）
            ---@field maxBlocking? number 内环最大不可通行/水域地块数（默认 2）
            ---@field minHills? number 内环最小丘陵数（默认 2）

            ---@class UncivMapStartingLocation
            ---@field x number
            ---@field y number
            ---@field nation string 关联的文明（nation）名（可为空）

            -- GetMapScriptInfo 返回值约定
            ---@class UncivMapScriptInfo
            ---@field name string 显示名（新建游戏界面）
            ---@field description string 描述
        """.trimIndent()
    }

    /** Pure generation - the tests call this; the docs task writes the result to disk. */
    fun generate(): String = generateLuaTypeDefinitions(
        headerLines, ownerOrder, classNameByOwner, LuaMapGenApiDocs.entriesByName,
        fieldComment = { it.descZh }, extraSections = extraSections
    )

    /** Writes the generated definitions into the docs folder (generateDocs task, working dir = assets). */
    fun write() {
        File(outputFileName).writeText(generate())
    }
}
